### ISSUE TITLE
Use Image Gallery plugin?

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/wp-news#103]
Should the image galleries at the bottom of some articles be snazzy?

http://munews.wpengine.com/university-health-sciences-center-to-offer-demonstrations-at-third-annual-atlanta-science-festival-exploration-expo/

**Comment by maconmatt** [comment]
Is this something that could be programmatically added? If not, I wouldn't spend a ton of time on these past articles. I've already talked with Kyle, etc. about the possibility of "snazzy" galleries for future articles, but i'm not too worried about these past articles.

**Comment by Sporkyy** [comment]
Yes, it can be changed after-the-fact. All the galleries in the import use the simplest shortcode [`gallery]`. Change how that works on the back-end and it will change everything.

https://wordpress.stackexchange.com/questions/91381/change-the-output-for-gallery-shortcode

2-3 images, especially these old ones, aren't anything to worry about. But 10 images in a new article somebody cares about? It's the same solution. _For later._
