### ISSUE TITLE
How do we feel about items with multiple sidebars because of multiple categories? 

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#105]
http://munews.wpengine.com/commencements-to-include-nearly-2000-students-in-macon-atlanta-and-savannah/

**Comment by maconmatt** [comment]
Ooh, good one. Let me think on this one.

**Comment by maconmatt** [comment]
Let's shelve this one. If it becomes more of an issue down the road, we'll revisit it.
