### ISSUE TITLE
Category accents are red on individual posts

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#106]
![image](https://user-images.githubusercontent.com/22402707/37121677-f42f2732-222b-11e8-9a2b-1add23ec91b4.png)

http://munews.wpengine.com/commencements-to-include-nearly-2000-students-in-macon-atlanta-and-savannah/

**Comment by cinakur** [comment]
change to orange

**Comment by maconmatt** [comment]
Yep, agreed.

**Comment by cinakur** [comment]
Added in Customize CSS 

```
.s_header_wraper .post-category a, .post-category a {
	background-color: #c95106;
}
```
