### ISSUE TITLE
Change author of Todd's articles to...?

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#107]
to who? News @ Mercer? 

[Todd's Articles](http://munews.wpengine.com/author/sayre_ts/)

I mean, we can keep them as Todd, but figured it's worth changing in a batch. :) 

[Resource](http://www.wpbeginner.com/beginners-guide/how-to-change-the-author-of-a-post-in-wordpress/)

**Comment by maconmatt** [comment]
Changed author to News@Mercer.
