### ISSUE TITLE
Color of visited links in footer persists, even on reload

### ISSUE THREAD

**Issue by maconmatt** [merceruniversity/wp-news#108]
<img width="358" alt="screen shot 2018-03-07 at 8 28 00 pm" src="https://user-images.githubusercontent.com/33905319/37127977-1a736e52-2246-11e8-8c34-29fb11ab053a.png">

**Comment by cinakur** [comment]
@maconmatt do you want them to stay orange?

**Comment by maconmatt** [comment]
@elcopeland yes let's keep them orange

**Comment by cinakur** [comment]
@maconmatt orange to start, orange when visited?

**Comment by cinakur** [comment]
(uh so I actually fixed this today.) 

In Customize > Additional CSS

```
/* Make footer links orange and stay orange*/

.footer .textwidget a:visited{
	color: #c8541e;
}
```
