### ISSUE TITLE
mu-research

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#25]
- [ ] add element on index page 
- [ ] add feed URL to element
- [ ] delete old element
- [ ] submit page
- [ ] verify new element renders correctly

**Comment by cinakur** [comment]
http://research.mercer.edu/news/2017/

**Comment by Sporkyy** [comment]
Those old links to news.mercer.edu work because I've got redirects in place.
Those old links to www2.mercer.edu stopped working years ago and nobody noticed.
