### ISSUE TITLE
Documentation: How to choose and add a Featured Image

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#42]
- [x] Where it goes (Archive, Home Page)
- [x] Aspect Ratios
- [x] Gallery Options

**Comment by maconmatt** [comment]
The theme documentation recommends that the featured images be 1050px x 600px...but I'm not liking how that is laying out. I'm still working on the ideal ratio and will report back.

**Comment by maconmatt** [comment]
The size we're going to go with is retina-ready 1800x1200. Thanks!

**Comment by cinakur** [comment]
@maconmatt are you saying you save out a 3600x2400 or is 1800x1200 ok

--- confirmed via Slack 1800x1200

**Comment by cinakur** [comment]
[Doc Link](https://docs.google.com/document/d/1TSbNHrfGM0cADpygngI6APnS0ARpl13p5bmQcKLVLr0/edit#bookmark=id.4xyjyjn6r6qf)
