### ISSUE TITLE
Determine categories

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/wp-news#48]
# Categories are generally nouns; they are parts of the university.

| Name                 | Slug                   | Notes     |
|----------------------|------------------------|-----------|
| General                 | general                   | Catch-all |
| Business & Economics | business-and-economics |           |
| Education            | education              |           |
| Engineering          | engineering            |           |
| Health Professions   | health-professions     |           |
| Law                  | law                    |           |
| Liberal Arts         | liberal-arts           |           |
| Medicine             | medicine               |           |
| Music                | music                  |           |
| Nursing              | nursing                |           |
| Penfield             | penfield               |           |
| Pharmacy             | pharmacy               |           |
| Theology             | theology               |           |
| Working Adults       | working-adults         |           |
| Health Sciences      | health-sciences        |           |

**Comment by cinakur** [comment]
Wiki here: https://github.com/InteractiveDesignAndDevelopment/wp-news/wiki/Categories

**Comment by cinakur** [comment]
Question: What do we do for Centers? 

E.G. CCJ, HSC, etc.

**Comment by maconmatt** [comment]
These do not need categories. CCJ is considered under Liberal Arts, HSC is an umbrella for the 4 medical-related schools and colleges. There is no need to separate it out, though. All of the other centers we can think of reside within the 12 schools and colleges.

**Comment by cinakur** [comment]
@maconmatt heard. Would like a little bit of info on these Categories: 
- is their only purpose to generate the Custom News feeds on teh homepages that already exist?
- What do you think about the "mission statement" at the top of the page?

**Comment by maconmatt** [comment]
Yes, pretty much. Although, they may be used to populate other various feeds/elements on the news site, like the homepage. I'm not sure i'm following your question about the mission statement.

**Comment by cinakur** [comment]
Ok, sounds good. We'll have CommonSpot elements only for the listed Categories here, and then the tag "Featured" and the tag "Research." 

The mission statement was us trying to decipher a rule for the group as a whole vs. what constitutes a tag. "Categories are generally nouns; they are parts of the university." vs the one on the tags page which reads, "Tags are generally verbs; they are things the university does."

**Comment by maconmatt** [comment]
I have added the categories to the site.

**Comment by cinakur** [comment]
Thanks Matt! Noted and closed.
