### ISSUE TITLE
Determine tags

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/wp-news#49]
# Tags are generally verbs; they are things the university does.

**Comment by cinakur** [comment]
|         Name         |      slug       |                                           notes                                           |
| -------------------- | --------------- | ----------------------------------------------------------------------------------------- |
| Featured             | featured        | Promotes to mu-www                                                                        |
| Student Achievements | students        |                                                                                           |
| Faculty Achievements | faculty         |                                                                                           |
| Staff                | staff           |                                                                                           |
| Trustees             | trustees        |                                                                                           |
| Research             | research        |                                                                                           |
| Alumni               | alumni          |                                                                                           |
| Academic Events      | academic-events | Forums, Conferences, Panels, Discussions, Symposiums, Workshops for Academics in Academia |
| Events               |                 | Homecoming, Athletics watch parties, Athletic events,                                     |
| Administration       | administration  | Trustees Decisions, new faculty and staff, promotions and transfers                       |
| Service              | service         | things that the school does for the community                                             |
| The Arts             | arts            | art stuff                                                                                 |

**Comment by cinakur** [comment]
Wiki here: https://github.com/InteractiveDesignAndDevelopment/wp-news/wiki/Tags

**Comment by maconmatt** [comment]
Did we discuss having these pre-populated tags, or were Kyle and I going to add these as we see fit going forward?

**Comment by cinakur** [comment]
Mostly we were looking for featured and research and got carried away. Basically, if there needs to be a feed for it, we need to know. If featured and research are the only two then we can just pull those and close this issue.

**Comment by cinakur** [comment]
So we'll just stick with featured tags for now and you guys will add more down the road.
