### ISSUE TITLE
Article redirects (for news.mercer.edu and archive.mercer.edu)

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/wp-news#51]
What kind of redirect strategy should we use when launching the site?

We're moving the news.mercer.edu domain, so the redirects will all have to be created in the WordPress site. We've done this sort of thing before, but this has some additional wrinkles.

Take this article URL.

http://archive.mercer.edu/www2/www2.mercer.edu/News/Articles/2006/060211baseball.html

I changed the Permalink Settings to *Post name (http://munews.wpengine.com/sample-post/)*.

So this article URL works.

http://munews.wpengine.com/060211baseball/

I can set up .htaccess redirects that work with that since I'm using the file names as the post slugs.

It can work for both the MCMS and CommonSpot news articles.

**Comment by maconmatt** [comment]
This sounds good to me.

**Comment by cinakur** [comment]
Agreed! @Sporkyy how do you want this noted before I/you close this issue. Wiki?

**Comment by maconmatt** [comment]
I think this issue has been solved, right @Sporkyy ?

**Comment by Sporkyy** [comment]
No, it's resolved now that I've actually implemented them.
