### ISSUE TITLE
Create and brand individual Category pages

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#53]
Create pages, add feeds. 

- [x] Business & Economics
- [x] Education
- [x] Engineering
- [x] Health Professions
- [x] Law
- [x] Liberal Arts
- [x] Medicine
- [x] Music
- [x] Nursing
- [x] Penfield
- [x] Pharmacy
- [x] Theology
- [x] Working Adults
- [x] Health Sciences

**Comment by maconmatt** [comment]
➤ Matthew Smith commented:

This is a test comment from Asana.
