### ISSUE TITLE
Determine stock featured images for posts

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#54]
At least three, please. (You can provide as many as you want)

**Comment by maconmatt** [comment]
I'll try to get you these today.

**Comment by maconmatt** [comment]
...and i'm woefully behind on this. I'll get you some images before the holidays for sure.

**Comment by maconmatt** [comment]
These are the images to add to the media gallery for "stock" purposes:

Macon: http://gallery.mercer.edu/Featured-Images/i-PnVxVC4/A
Admin: http://gallery.mercer.edu/Featured-Images/i-62ZmPfj/A
Cruz: http://gallery.mercer.edu/Featured-Images/i-VwSszvF/A
Bear: http://gallery.mercer.edu/Featured-Images/i-8ZwC4Sn/A
Bridge: http://gallery.mercer.edu/Featured-Images/i-mf8TMbd/A
Atlanta: http://gallery.mercer.edu/Featured-Images/i-C4K9njP/A

**Comment by maconmatt** [comment]
Once that is done, this issue can be "closed".

**Comment by Sporkyy** [comment]
These all seem pretty specific. Are there any preferable ones that I can randomly assign to old articles?

**Comment by maconmatt** [comment]
Hmmm... we probably need a few, huh? This is tricky, because virtually all of our photos are specific to a location.

**Comment by Sporkyy** [comment]
There are thousands of old articles. 3000+ between MCMS and CommonSpot. I think I'm using 5 images now, randomly, and the repeats are annoying when they're subsequent.

So maybe 10 random stock images? Even just variations on a few would be good.

**Comment by maconmatt** [comment]
Ok. I'll see what i can find.
