### ISSUE TITLE
Identify if we want to keep trackbacks and ping backs active

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#56]
For importing post XML files

**Comment by maconmatt** [comment]
I've decide to deactivate trackbacks and pingbacks. They're a bit outdated and, in my opinion, have more downsided than up. I'll close this issue.

**Comment by Sporkyy** [comment]
I'm going to start a wiki page for the import procedures and I'll note that there at some point. And then I'll re-close it.

**Comment by cinakur** [comment]
[Added to Wiki](https://github.com/InteractiveDesignAndDevelopment/wp-news/wiki/Import-Procedures)
