### ISSUE TITLE
Install Post category-specific sidebars plug-in

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#57]

**Comment by cinakur** [comment]
[Conversation from WPstackexchange](https://wordpress.stackexchange.com/questions/106399/dynamic-sidebar-based-on-category)

Couple options
- [Conditional Widgets](https://wordpress.org/plugins/conditional-widgets/)
- [Dynamic Widgets](https://wordpress.org/plugins/dynamic-widgets/)
- [WPMU DEV Custom Sidebars Pro](https://premium.wpmudev.org/project/custom-sidebars-pro/)

**Comment by cinakur** [comment]
@maconmatt you still thinking through adding content to posts of a certain category that direct back to the law school? we might can kill two birds with one stone here.

**Comment by maconmatt** [comment]
Yes, @elcopeland, i think that would be a great feature to have. Do one of these plugins accomplish that?

**Comment by cinakur** [comment]
This might need to be an in-person convo, since you did voice a concern about muddying the widget view...however, I think that for what we're looking to do that maaaay be the best option. Conditional or Dynamic widgets, you make them all on the widget page and determine what actual page/post they're on at the same time.

**Comment by cinakur** [comment]
I'm going to try Dynamic Widgets first, it's been most recently updated.

**Comment by cinakur** [comment]
:+1:
