### ISSUE TITLE
Media galleries containing special image galleries?

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#58]
Research what plug-ins can do what with the media gallery (specifically, the goal for this is to ID how to handle stock images)

**Comment by cinakur** [comment]
- https://codecanyon.net/item/media-library-categories-premium/6691290 (Categories)
- https://wordpress.org/plugins/enhanced-media-library/ (Categories)
- https://wordpress.org/plugins/media-library-plus/ (Folders)
- https://themeisle.com/blog/wordpress-media-folders-organize/ (Folders)
- http://www.wpsuperstars.net/wordpress-media-library/ (Folders)

**Comment by cinakur** [comment]
@maconmatt @Sporkyy 

Do you think Add Categories ([example](https://wordpress.org/plugins/enhanced-media-library/)) or add Folders ([example](https://themeisle.com/blog/wordpress-media-folders-organize/))? I feel like the latter is overkill if we just want to have a few images that are stock images.

Honestly, it all could be overkill if instead we just added "Stock" or some other identifying key word in the title. Thoughts?

**Comment by maconmatt** [comment]
Yes. I'm starting to wonder if this is overkill...at least for "News".

**Comment by cinakur** [comment]
Answer: no need for this round.
