### ISSUE TITLE
Test Kraken.io

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#59]
- [x] User Experience
- [x] Document how to use
- [x] Determine take-aways

**Comment by cinakur** [comment]
@Sporkyy please shoot me [credentials.]

**Comment by cinakur** [comment]
uh, so users really...do nothing. It's literally all on the backend from here on out. 

@Sporkyy and @maconmatt -- I'm on the third page of media images and we're at 50% of our Kraken quota. Should I pump the breaks on optimizing stuff? It's all the older images anyway. 

ETA we're at 60% "Overall, you have optimized 28.19 MB of images (786 files) saving 10.36 MB (37%) total file size."

**Comment by Sporkyy** [comment]
@elcopeland I'd stop because I'm going to blow away our quota when I do the CS import.

I'm going to try and get that done before leaving for the holidays+vacation.

**Comment by cinakur** [comment]
roger wilco
