### ISSUE TITLE
Hashes following post

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#66]
http://munews.wpengine.com/121101_mercer-to-dedicate-myers-welcome-center-friday-building-is-the-universitys-first-leed-certifi/

![screen shot 2018-01-31 at 1 13 28 pm](https://user-images.githubusercontent.com/22402707/35639571-90cdf6aa-0688-11e8-95d8-781e0e3b6b70.png)

**Comment by cinakur** [comment]
other cases: 
- http://munews.wpengine.com/120911_mercers-mcduffie-center-for-strings-and-its-namesake-to-be-featured-this-week-on-national-rad/
- http://munews.wpengine.com/120808_mcduffie-loves-macon-free-community-concert-a-pre-labor-day-gift-to-the-world-renowned-musici/
- http://munews.wpengine.com/120713_mercer-professors-selected-as-governors-teaching-fellows/
- http://munews.wpengine.com/120423_the-grand-opera-house-announces-2012-13-variety-series/

**Comment by Sporkyy** [comment]
This is editorial. Do we change this on ex/import?

See also: #68

**Comment by cinakur** [comment]
Issue moved to [InteractiveDesignAndDevelopment/mcms-news-export #10](https://github.com/InteractiveDesignAndDevelopment/mcms-news-export/issues/10) via [**ZenHub**](https://www.zenhub.com/)
