### ISSUE TITLE
-30- following posts

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#68]
cases: 
- http://munews.wpengine.com/120827_mercer-law-school-welcomes-inaugural-llm-class/
- http://munews.wpengine.com/120821_princeton-review-mercer-no-8-for-intramural-involvement/
- http://munews.wpengine.com/120816_mercers-largest-entering-class-set-to-move-in-saturday/
- http://munews.wpengine.com/120806_mercer-university-names-taylor-as-2012-griffith-scholar/
- http://munews.wpengine.com/120719_peyton-anderson-foundation-awards-1-million-grant-to-fund-newsroom-in-center-for-collaborativ/
- http://munews.wpengine.com/110818_chapel/

**Comment by Sporkyy** [comment]
This is editorial. Do we make this change on ex/import?

See also: #66

**Comment by maconmatt** [comment]
What exactly is it? Where did it come from?

**Comment by Sporkyy** [comment]
Vanderhoek.

**Comment by maconmatt** [comment]
Wait...so it is (was) designed to be there?

**Comment by cinakur** [comment]
As far as we can tell, yes. We don't know why it was started or why it stopped.

**Comment by cinakur** [comment]
Issue moved to [InteractiveDesignAndDevelopment/mcms-news-export #12](https://github.com/InteractiveDesignAndDevelopment/mcms-news-export/issues/12) via [**ZenHub**](https://www.zenhub.com/)
