### ISSUE TITLE
Style Author Accounts/Pages

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#78]
- [x] Who all should have accounts
- [x] Who should style them (do we want the authors to do their own?)

Maybe not all of them, just the big ones: 
- Billie
- News@Mercer
- etc?

**Comment by maconmatt** [comment]
➤ Matthew Smith commented:

Good call. I thought about his a while back and never added it to the list.

**Comment by maconmatt** [comment]
➤ Matthew Smith commented:

Another test comment. (I'm working on Asana/Github integration)

**Comment by maconmatt** [comment]
Kyle and I are going to request and manually enter a photo, and brief bio for our contributors.
