### ISSUE TITLE
Add ellipses to long-running title text on homepage slider

### ISSUE THREAD

**Issue by maconmatt** [merceruniversity/wp-news#88]
Hopefully, one of us can figure this one out?

<img width="1273" alt="screen_shot_2018-02-08_at_11_33_50_am" src="https://user-images.githubusercontent.com/33905319/35985307-5bf1afb6-0cc4-11e8-842f-f3b7f251429c.png">

**Comment by Sporkyy** [comment]
The simplest vanilla-CSS solution is stymied by multi-line text. Everything else is a little hacky.

**Comment by maconmatt** [comment]
I'm guessing the solution they use for the post excerpt in the above image is done with character counts?

**Comment by Sporkyy** [comment]
Looking at the other examples, the ellipses all appear after a word, so it's probably elastic.

_Ellipsis goes after the first word after 120 characters_ or something like that.

**Comment by Sporkyy** [comment]
But, yes, the ellipses are real text on the page. It's a server-side solution.

**Comment by maconmatt** [comment]
So, we can come up with something that will "work"?

**Comment by Sporkyy** [comment]
I don't know.

Looking at the number of characters to work with and the margin for error (error = flowing onto > 2 lines), I see a client-side solution being better. But those have pitfalls.

http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/

**Comment by maconmatt** [comment]
Theme developer is looking into this.

**Comment by maconmatt** [comment]
Developer has fixed the issue.
