### ISSUE TITLE
Add Faculty Notables feed to Homepage

### ISSUE THREAD

**Issue by maconmatt** [merceruniversity/wp-news#91]
- [x] Create Faculty Notables category
- [x] Create feed
- [x] Assign older articles from export with FN category

**Comment by Sporkyy** [comment]
I'll add the category in the export.

**Comment by maconmatt** [comment]
Perfect. Thanks!

**Comment by Sporkyy** [comment]
So, the programming I'm working on is like the below.

```
if the article has "faculty" and "notables" in the title
then give put it in the Faculty Notables category
else put it in the General category
```

So every post will only have one category, correct?

**Comment by maconmatt** [comment]
Yes, that is correct.
