### ISSUE TITLE
Rename and Reorder mobile navigation list

### ISSUE THREAD

**Issue by maconmatt** [merceruniversity/wp-news#92]
<img width="296" alt="screen shot 2018-02-13 at 11 27 21 am" src="https://user-images.githubusercontent.com/33905319/36161167-01ca68d4-10b1-11e8-9b50-de6639fd98dc.png">

**Comment by maconmatt** [comment]
I've added both of you in case you can get to it and update it sooner than i can. I think "Top Menu" should be renamed to "University Menu" and should be located below the "Main Menu"

**Comment by maconmatt** [comment]
Or, even better...maybe "Top Menu" shouldn't even show up on the mobile version.

**Comment by cinakur** [comment]
- [x] Rename "Top" to "University" 
- [x] Move "University" Menu to bottom on mobile view

**Comment by cinakur** [comment]
Renamed Top to "University Links"
Renamed Main to "Mercer News Menu" 

Looks like the name of the menus as seen are Theme-defined, not user defined. 

--- 

Looks like to mod the menu set up, we'd need to hack up the php in our The REX: Theme Header from the parent theme (header.php)

We should discuss how we want to track and test these type of updates. I personally haven't done this. 

`<div id="main-mobile-menu">
            <div class="block">
                <div id="mobile-inner-header">
                    <h3 class="menu-title">
                        <?php echo bloginfo( 'name' );?>
                    </h3>
                    <a class="mobile-menu-close" href="#" title="Close"><i class="fa fa-long-arrow-left"></i></a>
                </div>
                <?php if ( isset($bk_option ['bk-header-top-switch']) && ($bk_option ['bk-header-top-switch'] == 1) ){ ?>
                     <div class="top-menu">
                        <h3 class="menu-location-title">
                            <?php esc_html_e('Top Menu', 'the-rex');?>
                        </h3>
                    <?php
                    wp_nav_menu( array( 
                        'theme_location' => 'menu-top',
                        'depth' => '3',
                        'container_id' => 'mobile-top-menu' ) );
                    ?>
                    </div>
                <?php }?>
                <div class="main-menu">
                    <h3 class="menu-location-title">
                        <?php esc_html_e('Main Menu', 'the-rex');?>
                    </h3>
                    <?php
                    wp_nav_menu( array( 
                        'theme_location' => 'main-menu',
                        'depth' => '3',
                        'container_id' => 'mobile-menu' ) );
                    ?>
                </div>
            </div>`

**Comment by cinakur** [comment]
- [x] Add HOME to News Menu
