### ISSUE TITLE
look at how tables are set up in theRex

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/wp-news#94]
- [x] ID how the Rex theme handles it
- [x] Give to Matt on how he'd like to style tables

**Comment by cinakur** [comment]
@maconmatt 

Here is how the Rex handles tables. 

http://munews.wpengine.com/test-penfield-post/

Is that acceptable or would you like other stylings?

**Comment by maconmatt** [comment]
It's ok, but why doesn't it span the entire area of the body?

**Comment by cinakur** [comment]
We can make table widths 100%, that's not a problem :)

**Comment by maconmatt** [comment]
I don't see any reason to change it at the moment, then

**Comment by cinakur** [comment]
👍 

(Added 
`table {
	 width: 100%;
}` to Additional CSS tab
