### ISSUE TITLE
Double news articles

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/wp-news#96]
This is a **totally, completely and utterly** valid part of the export, so it's going to have to be fixed on the new in-WordPress news.mercer.edu side of things before launch.

I think there may be more, but I wasn't looking for them.

http://munews.wpengine.com/121109_woodruff-foundation-awards-1-5-million-grant-to-fund-new-home-for-mcduffie-center-for-strings/

http://munews.wpengine.com/121109_woodruff-foundation-awards-1-5-million-grant-to-fund-new-home-for-mcduffie-center-for-strings-2/

**Comment by maconmatt** [comment]
Am i good to research/fix these now?

**Comment by Sporkyy** [comment]
In truth. I wouldn't. Try to wait until the last minute, just in case.

**Comment by maconmatt** [comment]
De-duped everything that needed it.
